### ISSUE TITLE
Printing student files - remove extraneous newlines

### ISSUE THREAD

**Issue by tompostler** [ludvi025/graid#1]
At the end of student files, you should make it so that any extra empty newlines are stripped from the file to reduce unnecessary output.

**Comment by ghost** [comment]
I added code to printCode in lib\runner\runner.py to remove the extra lines from the end of the file before printing.  I wasn't able to check it in the context of the script, but it works on lists as would be generated by reading a file.

**Comment by ludvi025** [comment]
I checked this and got an index out of range error, so I fixed that and now we're good.
