### ISSUE TITLE
People with more than two names get recorded incorrectly.

### ISSUE THREAD

**Issue by ludvi025** [ludvi025/graid#13]
Quote from @darebear:

As I recall, the main issue is when assigning student IDs. The script will look at the student info file and will not match students that have more than two names since there is a discrepancy between the student info name fields and the ones the program is looking for. 
For example, Adam Jay III may have his last name classified as "Jay III" in the student info file, but the script may be looking for just "III". That said, since there are only a few people, it's easy to go back and modify the student file to match what the script is looking for.. 
We tried doing that on Saturday but something else was causing the script to crash. 
You're welcome to replicate the error using the scripts as they are up to now and the student_info file found in:

`csci1133/student_info/student_infomation`

Or something like that. There should only be one info file in that directory.

**Comment by ludvi025** [comment]
See `lib.moodie.export_gradebook.py` and `lib.tools.sub_parser.py`.

**Comment by tompostler** [comment]
I found a way to map from the Moodle unique id that is in the filenames of the students' submissions back to email addresses. I believe that would resolve this problem?

**Comment by ludvi025** [comment]
Yep

**Comment by ludvi025** [comment]
Fixed: 
85ea95f02c246731b441896114ec4addf9e28f07
231aaa3fd9c6b5bde1556fd952325359413a7de9
